# Generated by Django 6.0 on 2026-01-05 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditlog',
            old_name='performed_by',
            new_name='user',
        ),
    ]
